### PR TITLE
Export saved books to JSON

### PR DESCRIPTION
**Pull request by Tom-private**
## Summary of change

This PR adds a button to the settings view that the user can use to export all their saved books as JSON.
Also, a new method is implemented in the BookService which returns a JSON representing all books in the database.

## Additional context

image

## Related issue
#7

### CODE REVIEW

**Comment by Tom-private** [comment]
This is a draft because:
- at the moment, only a dummy JSON is returned, the real functionality has yet to be implemented
- the UI may need some changes so this PR serves as chance to already have a look at it

**Comment by knjk04** [comment]
> the UI may need some changes so this PR serves as chance to already have a look at it

UI looks good. I like that you added a download button. 

(It may seem strange that there's no structure yet on the settings page, but we're looking for this to be designed -- see #264)

**Comment by Tom-private** [comment]
I would like some feedback on the structure of the JSON.

At the moment, I just took what Jackson gave me, but maybe some values should be ignored (e.g. predefined shelf: shelfName and predefinedShelfName are the same). How do you want the json to look like?

The id has to be removed, I will work on that now.

**Comment by knjk04** [comment]
> e.g. predefined shelf: shelfName and predefinedShelfName are the same)

Agreed. Perhaps we should only keep the `shelfName` since that's what `toString()` of the `PredefinedShelf.ShelfName` gives (so we could add a function to the enum that does the reverse later -- goes from a string representation to a PredefinedShelf)

Other things:

- Minor, but could you change "ArrayList" to "AllBooks" instead?
- The dates by default are verbose, so you could write the dates as timestamps instead (e.g. `1920-11-08`) in a yyyy-MM-dd format?

I've never used Jackson before, so I'll take a look and see if there's anything else, but this looks good to me. With the above changes made, it'll be even better.

**Comment by Tom-private** [comment]
Update: 
This is a draft because:
- ~~at the moment, only a dummy JSON is returned, the real functionality has yet to be implemented~~ -> is implemented
- ~~the UI may need some changes so this PR serves as chance to already have a look at it~~ -> UI was approved
- there are no tests yet.

**Comment by knjk04** [comment]
Possible idea for a test: remove all books and then create one book in each of the four predefined shelves. If you write the JSON for this by hand, you can then output what the app generates and test whether the two files are the same.

What do you think?

**Comment by Tom-private** [comment]
My idea for a test is to create two books, one with only the mandatory fields set and one with all fields set. So we can make sure, that missing and existing values for all fields are correctly displayed in the json.
(The book that has values for all fields could not exist like this in the actual app, but I think that that's ok, because that does not matter for the test.)
I wouldn't create one book for each shelf, because the only things that change are the value for the shelf and which fields do have values. Just creating one book with all fields serves the same purpose of testing all fields at least one time but produces a smaller, more comprehensible test.

**Comment by knjk04** [comment]
OK, that's fine. I agree with your reasoning. Let me know when you're ready for a review

**Comment by Tom-private** [comment]
I would say that it is ready for review, but i don't know why the build is stuck in queue.

**Comment by Tom-private** [comment]
In travis itself it is green.

**Comment by knjk04** [comment]
I don't know why Travis does that sometimes. I re-ran the build and it's showing as passed now on GitHub

**Review by knjk04 — APPROVED** [review]
Thanks a lot for this! Great work! This was an important feature (highlighted in our roadmap), so it's great that it's done to a high standard

**Comment by Tom-private** [comment]
Thank you very much. :)

**Pull request merged**
