### PR TITLE
Improve styling of add shelf

### PR DESCRIPTION
**Pull request by Tom-private**
## Summary of change

This PR adds styling for the add shelf form.
To differentiate between the addBookForm and the addShelfForm, I use JavaScript to set a describing class to the overlay of the corresponding form when it is opened.

## Additional context
width >= 37em:
image

width < 37em:
image

## Related issue

#292

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks, that looks a lot cleaner than what we currently have. 

To keep things consistent, could you
- Align the save button vertically with the left of the shelf text field?
- Change the button text from 'save shelf' to 'save?

I appreciate this wasn't mentioned in the issue description, so apologies.

**Comment by Tom-private** [comment]
No problem, these were not big changes.

**Review by knjk04 — APPROVED** [review]
Thanks, this is great!

**Comment by Tom-private** [comment]
I really appreciate that you always say thank you in the end. It makes me want to help out more and make an effort. :)

**Comment by knjk04** [comment]
Thanks for those kind words! I'm really grateful that so many people have contributed to the project, and lots of our contributors, such as yourself, have contributed multiple times!

**Pull request merged**
