### PR TITLE
Change the database from h2 to MySQL

### PR DESCRIPTION
**Pull request by ChFlick**
## Summary of change

Change the database from h2 to MySQL

## Additional context

I also added [flyway](https://flywaydb.org/) to the project to get the database under version control and enable db schemas, though I don't know if you're okay with it @knjk04, as the migrations have to be maintained as well.

## Related issue

#61

### CODE REVIEW

**Comment by ChFlick** [comment]
I'd use [testcontainers](https://www.testcontainers.org/) for the integration tests / tests accessing the db.

**Comment by knjk04** [comment]
I'm happy with Flyway, thanks for adding that. Thanks also for the Testcontainers suggestion!

**Comment by knjk04** [comment]
Thanks a lot for this! I'll review it shortly

**Comment by knjk04** [comment]
Is this ready for a review (I saw that you added more commits)?

**Comment by ChFlick** [comment]
It's ready to be reviewed. I just wanted to keep it up to date to the master.

**Comment by knjk04** [comment]
Ah, I see. Thanks!

**Comment by knjk04** [comment]
I had some issues running `docker-compose up`, so I'll try again when I'm back at home this week.

I think docker-compose is also a prerequisite?

**Comment by knjk04** [comment]
Thanks for resolving the merge conflict.

Does the app still run for you? On my end, I'm getting the following:
```
Caused by: org.flywaydb.core.api.FlywayException: Validate failed: 
Detected failed migration to version 002 (CREATE AUTHOR)
```

(I'm new to Flyway)

**Comment by knjk04** [comment]
Ah, thanks for that. I was getting some issue when I tried to resolve the conflict earlier and I did run clean, but to no avail. Not sure why it worked this time.

Anyway, thanks a lot for this PR!

**Pull request merged**
