### PR TITLE
add a placeholder for the book rating form field

### PR DESCRIPTION
**Pull request by tmrd993**
## Summary of change

Added the placeholder message "Enter a rating" to the book rating form field

## Additional context
iss175Screen

## Related issue

https://github.com/knjk04/book-project/issues/175

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for this!

I know you've already made the PR, but could you comment on the issue asking to be assigned (our process has changed since when you first contributed -- we now require a request to be assigned before working on the issue to avoid duplicated work)? It also means that we can easily track who worked on the issue on our project board without having to follow a trail to the linked PR.

**Comment by tmrd993** [comment]
Done. I'll keep it in mind next time.

**Comment by knjk04** [comment]
The change itself is fine, but the branch name does include the issue number. Could you change the branch name accordingly (e.g. to `add-rating-placeholder-178`)? This makes it easy to see from the commit alone which issue it was tackling (this is also a part of our contributing guidelines).

**Comment by tmrd993** [comment]
closed in favor of https://github.com/knjk04/book-project/pull/179

**Pull request closed without merging**
