### PR TITLE
Fix overlapping form labels

### PR DESCRIPTION
**Pull request by Tom-private**
## Summary of change

This PR solves the problem, that the different input fields in the form to add a book, did overlap when the screen was not wide enough.

## Additional context
width >= 70em:
image

width >= 37em:
image

width < 37em:
image

## Related issue
 
#57

### CODE REVIEW

**Comment by Tom-private** [comment]
This also affects the form for adding a custom shelf. However, the only effect is, that the size of the "Add shelf"-form will not change dynamically, but suddenly when the thresholds are crossed.
I do not think, that this is a big problem.

**Comment by knjk04** [comment]
Thanks, this is excellent! 

I've merged in your review PR, so could you please rebase? I just want to ensure that this still works with the new review field. 

> This also affects the form for adding a custom shelf. However, the only effect is, that the size of the "Add shelf"-form will not change dynamically, but suddenly when the thresholds are crossed.
I do not think, that this is a big problem, it is barely noticeable.

Could you create a new issue for this? It's not a huge problem now, but it would be good to make that smoother in the future. For now, this is great!

**Comment by Tom-private** [comment]
> Could you create a new issue for this?

I can do that, but what should the scope for that issue be?
A: resize the Add book form dynamically when site is resized (so how it was before this change)
B: add styling for the Add book form -> how exactly? (I don't mean to offend you, but I think the form looked somewhat strange, even before my change)

**Comment by knjk04** [comment]
> I don't mean to offend you, but I think the form looked somewhat strange, even before my change

No, that's fine. What about it do you find strange?

**Comment by Tom-private** [comment]
Its just my perception, I am not sure how to put it in words. I just think it looks crooked(?) / unfinished when looking at these pictures:
image
image
The save button looks too wide, the input field too small in comparison. The scroll bar irritates me.

**Comment by knjk04** [comment]
I definitely agree with that. I've been thinking about that ever since I added that, but I never created an issue for that (I'll do that later today). 

Do you have any feedback for the book form?

**Comment by Tom-private** [comment]
> Do you have any feedback for the add book form?

Oh, my mistake. I meant the Add Shelf form. Add book looks nice now, I think.

The difficulty is, that we rely on the "overlay" element to set the width of the form. This overlay has no class which we can use to address the add book and add shelf forms separately.

As far as my research told me, a class can only be set to the overlay via JavaScript (like find all overlay-elements and add class "bookFormOverlay" to the one containing the bookForm and class "addShelfOverlay" to the one containing the addShelfForm).

**Comment by knjk04** [comment]
Thanks, that's good to know

**Review by knjk04 — APPROVED** [review]
Thanks a lot! Great work!

**Comment by Tom-private** [comment]
Thank you. I am glad that my PRs are getting better. :)

**Pull request merged**
