### PR TITLE
Added congratulatory message for completing set goal for pages.

### PR DESCRIPTION
**Pull request by tjrelyts**
## Summary of change
I have implemented functionality for displaying the congratulations message when you reach your set goal for pages. 
It also displays progress properly.

## Additional context
image

## Related issue

https://github.com/knjk04/book-project/issues/137

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks! I'll review this shortly

**Comment by knjk04** [comment]
A couple of things I spotted from a quick skim before a full review:

- Merge conflicts?
- PascalCase used for method and parameter names (e.g. `public static int ToReadFromStartOfYear(int ToReadThisYear)`). They should be camelCase
- Could you delete the `pnpmfile.js`? Sorry about this. I've now added it to the gitignore
- `calculateProgressBooks()` and `calculateProgressPages()` are very similar. Could you refactor this to avoid code duplication?

Could you fix the above, please?

As ever, if you need any help, feel free to contact us over Gitter

**Comment by tjrelyts** [comment]
I'll take a look and see if I can figure it out.

**Comment by tjrelyts** [comment]
@knjk04 could you close this req

**Pull request closed without merging**
