### PR TITLE
Set fetch type to lazy in Book entity for Author and PredefinedShelf.

### PR DESCRIPTION
**Pull request by bhavika1**
## Summary of change

Set the fetch type of Author and PredefinedShelf from Eager to Lazy in the Book entity.

## Related issue

https://github.com/knjk04/book-project/issues/80

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for contributing! This works great!

One thing I noticed is that your fork is quite behind this repository's master branch. Could you bring your branch up-to-date and run the new unit tests? (If `PredefinedShelfTests` fail when you run all of the tests, try running it individually -- it should pass when you run it by itself). 

Once that's done, it should be ready to merge in.

**Comment by knjk04** [comment]
Thanks for doing that.

Are the tests passing on your end? They're all failing for me, both when I run them collectively and individually (LazyInitializationException)

**Comment by bhavika1** [comment]
I was getting this exception earlier but then I updated the pom.xml to resolve it.

It is working fine for me with the latest pom.xml which is committed.
All the test cases are also passing.

**Comment by knjk04** [comment]
Oh OK. I'll check again on my end.

**Comment by knjk04** [comment]
This is the stack trace I get when I run BookProjectApplication.java: https://gist.github.com/knjk04/ec7089596e5271894eb19a3227c1dfe2

I've tried it on a different machine, and I've had someone else try it as well. I'll have a look into this further tomorrow to see whether I can fix it

**Comment by bhavika1** [comment]
I can get this error if I make<enableLazyInitialization> tag as false in pom.xml.

**Comment by bhavika1** [comment]
I can get this error if I make enableLazyInitialization tag as false in pom.xml.

**Comment by knjk04** [comment]
OK, thanks for letting me know.

I'm still working on trying to get this to work on my side.

**Comment by knjk04** [comment]
Since the unit tests are passing on CI, it could just be something I'm doing wrong.

As `populateTestData()` inside the `PredefinedShelfService` is failing for me and others due to a LazyInitializationException, I tried annotating the method with @Transactional, but it's still not working yet. Any ideas?

**Comment by knjk04** [comment]
Unfortunately, I have not been able to get this to work. I've tried it on two Linux machines, one Windows PC and I've had someone else try it on their Linux machine. 

I'm keen to get this resolved. Could you send the Spring log (the output in the run window of IntelliJ, for example)?

**Comment by bhavika1** [comment]
I am running the code in eclipse. You can view the Spring log :
https://gist.github.com/bhavika1/9523b1bf6c4fe65c519b1e2b4b8f4b7d

**Comment by knjk04** [comment]
Thanks for sharing that.

Could you zip the project and send it over a file-sharing service, such as [Firefox Send](https://send.firefox.com/)?

Also, could you let us know
- which (Oracle JDK, OpenJDK, etc.) JDK you're using including the version number?
- what OS you're using (including the version number)
- what browser you're using (including the version number)

**Comment by bhavika1** [comment]
Firefox Send is showing that it is temporarily unavailable. I will send the code once it is available.
Other details are:
JDK: 13
OS: Windows 10
Browser: Chrome Version 83.0.4103.116
IDE: Eclipse IDE for Java Developers Version: 2019-09 R (4.13.0)
	 IntelliJ IDEA 2020.1.2 (Community Edition) - I tried running in IntelliJ also

**Comment by bhavika1** [comment]
Firefox Send is still not working. Do you want me to send the code via some other means (like Google Drive )?

**Comment by knjk04** [comment]
Yes, please

**Comment by bhavika1** [comment]
https://drive.google.com/file/d/1RwZ9kf5gzvR9G4XzrNV1pYNLQx1p7uyz/view?usp=sharing

**Comment by knjk04** [comment]
Thanks, I'll take a look shortly

**Comment by knjk04** [comment]
> Firefox Send is showing that it is temporarily unavailable. I will send the code once it is available.
> Other details are:
> JDK: 13
> OS: Windows 10
> Browser: Chrome Version 83.0.4103.116
> IDE: Eclipse IDE for Java Developers Version: 2019-09 R (4.13.0)
> IntelliJ IDEA 2020.1.2 (Community Edition) - I tried running in IntelliJ also

Are you using the OpenJDK, Oracle's or some other JDK?

**Comment by ChFlick** [comment]
Hi,
I just wanted to mention that it works fine for me on Manjaro Linux.
I tried it using OpenJDK 14 and OpenJDK 11, running `mvn test` from the cli.

**Comment by knjk04** [comment]
Thanks

**Comment by knjk04** [comment]
@ChFlick That is strange. Thanks for checking

**Comment by knjk04** [comment]
@bhavika1 With regret, I'm going to close this pull request and unassign you from the issue so that someone else can work on this issue. I appreciate that might be quite annoying and I fully appreciate the time and effort you put into this. Unfortunately, it would not make sense for us to merge this in if we cannot get it to compile.

**Pull request closed without merging**
