### PR TITLE
Add sort for AuthorName #94

### PR DESCRIPTION
**Pull request by nagasaichaitanya**
## Summary of change

Implemented Comparator for non primitve Data Types 

## Additional context
image

## Related issue

Issue #94

### CODE REVIEW

**Comment by nagasaichaitanya** [comment]
I had to close the old one as i had to update my fork with your master.  Would be great if you can find a solution to that formating code thing ;)

**Comment by knjk04** [comment]
Thanks for this, I'll take a look at it shortly. I've responded to your query on formatting on Gitter :)

**Comment by knjk04** [comment]
It looks like you're not using 2 spaces. Could you resolve this? If you're still having issues with formatting, let me know on Gitter so that I can assist you further

**Comment by nagasaichaitanya** [comment]
I managed to import the format.xml can you see if the conflicts are now gone

**Comment by knjk04** [comment]
2 spaces were used, but I've fixed them. I'll also resolve the conflicts.

Thanks again for the contribution!

**Pull request merged**
